#   input CreateUserInput {
#     clientMutationId: string!
#     name: string!
#   }
CreateUserInput:
    type: relay-mutation-input
    config:
        fields:
            name:
                type: "String!"

#   type CreateUserPayload {
#     clientMutationId: string!
#     user: User
#   }
CreateUserPayload:
    type: relay-mutation-payload
    config:
        fields:
            user:
                type: User
