Message:
    type: object
    config:
        resolveField: '@=resolver("App\\GraphQL\\Resolver\\MessageResolver", [info, value, args])'
        fields:
            text:
                type: String
            createdAt:
                type: String
            user:
                type: User

MessageConnection:
    type: relay-connection
    config:
        nodeType: Message!
