Query:
    type: object
    config:
        fields:
            user:
                type: User
                args:
                    id:
                        type: Int
                resolve: '@=resolver("get_user", [args["id"]])'
            users:
                type: '[User]'
                resolve: '@=resolver("get_users")'
            messages:
                type: '[Message]'
                resolve: '@=resolver("get_messages")'
