Query:
  type: object
  config:
    fields:
      node:
        type: Node
        args:
          id:
            type: ID
        resolve: '@=resolver("get_node", [args["id"]])'
      users:
        type: UserConnection
        argsBuilder: Relay::Connection
        resolve: '@=resolver("get_users", [args])'
      messages:
        type: MessageConnection
        argsBuilder: Relay::Connection
        resolve: '@=resolver("get_messages", [args])'
      slowQuery:
        type: SlowResult
        args:
          timeout:
            type: Int
        resolve: '@=resolver("get_slow_query", [args["timeout"]])'
