User:
  type: object
  config:
    interfaces: [Node]
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\UserResolver", [info, value, args])'
    fields:
      id:
        type: ID!
      userId:
        type: Int
      name:
        type: String
      messages:
        type: MessageConnection
        argsBuilder: Relay::Connection

UserConnection:
  type: relay-connection
  config:
    nodeType: User!
