User:
    type: object
    config:
        resolveField: '@=resolver("App\\GraphQL\\Resolver\\UserResolver", [info, value, args])'
        fields:
            name:
                type: String
            messages:
                type: MessageConnection
                argsBuilder: Relay::ForwardConnection

UserConnection:
    type: relay-connection
    config:
        nodeType: User!
